sudo: true

matrix:
  include:
  - language: java

    jdk: openjdk8

    services:
     - docker

    script: "./.travis/travis-run.sh"

    after_success:
      - "./.travis/travis-deploy.sh"

  - language: bash

    before_script:
        - sudo apt-get install shunit2

    script:
        - bash repairnator/docker-images/checkbranches-dockerimage/check_branches_test.sh
        - bash repairnator/docker-images/bears-checkbranches-dockerimage/check_branches_test.sh

branches:
  only:
  - master