language: java

sudo: true

jdk: openjdk8

before_install:
  - chmod +x -R travis/

script: "./travis/travis-run.sh"

cache:
  directories:
    - $HOME/.m2

before_cache:
  - rm -f $HOME/.m2/repository/fr/inria/spirals