
language: java

sudo: true

jdk: openjdk8

services:
 - docker


install: ./.travis/travis-before.sh

jobs:
  include:
    - stage: prepare cache
      script: ./.travis/travis-before.sh
      
    - stage: test
      script: ./.travis/travis-maven-repair.sh

    - stage: test
      script: ./.travis/travis-run.sh

    - stage: deploy
      script: ./.travis/travis-deploy.sh

branches:
  only:
  - master
