
language: java

sudo: true

jdk: openjdk8

services:
 - docker



jobs:
  include:
    - stage: prepare
      name: "prepare cache"
      script: ./.travis/travis-before.sh

    - stage: test
      name: "maven-repair"
      script: ./.travis/travis-maven-repair.sh

    - stage: test
      name: "repairnator"
      script: ./.travis/travis-run.sh

    - stage: deploy
      name: "deploy to Sonatype and Dockerhub"
      script: ./.travis/travis-deploy.sh
      if: branch = master

