
language: java

sudo: true

jdk: openjdk8

services:
 - docker

install: ./.travis/travis-before.sh

jobs:
  include:
    - stage: test
      script: ./.travis/travis-repairnator.sh
      script: ./.travis/travis-maven-repair.sh	

    - stage: deploy
      script: ./.travis/travis-deploy.sh

branches:
  only:
  - master