language: java

sudo: true

jdk: openjdk8

services:
 - docker

env:
  matrix:
  - SCRIPT="travis-repairnator.sh"
  - SCRIPT="travis-maven-repair.sh"


before_script:
  - sudo apt-get update
  - sudo apt-get install cloc -y
  - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - sudo npm install -g ajv-cli
  - sudo apt-get install shunit2

script: ./.travis/$SCRIPT

after_success:
  - "./.travis/travis-deploy.sh"

branches:
  only:
  - master