
language: java

sudo: true

jdk: openjdk8

services:
 - docker

install: true

jobs:
  include:
    - stage: test
      name: "repairnator"
      # the PR build is responsible for the tests, no need to have the branch/push build (Eclipse's Travis account is very busy)
      before_install: if [[ $TRAVIS_BRANCH != master ]]; then travis_terminate 0; fi
      install: ./.travis/travis-before.sh
      script: ./.travis/travis-run.sh

    - stage: deploy
      name: "deploy to Sonatype and Dockerhub"
      script: ./.travis/travis-deploy.sh
      if: type = push AND branch = master

