language: java

sudo: true

jdk: openjdk8

services:
 - docker

env:
  matrix:
  - SCRIPT="travis-repairnator.sh"
  - SCRIPT="travis-maven-repair.sh"


jobs:
  include:
    - stage: before
      script: "bash ./.travis/travis-before.sh"

    - stage: test
      script: ./.travis/$SCRIPT

    - stage: deploy
      script: ./.travis/travis-deploy.sh

branches:
  only:
  - master