
language: java

sudo: true

jdk: openjdk8

services:
 - docker



jobs:
  include:
    - stage: test
      name: "maven-repair"
      install: true
      script: ./.travis/travis-maven-repair.sh

    - stage: test
      name: "repairnator"
      install: travis_retry ./.travis/travis-before.sh
      script: travis_wait 30 ./.travis/travis-run.sh

    - stage: deploy
      name: "deploy to Sonatype and Dockerhub"
      script: ./.travis/travis-deploy.sh
      if: branch = master

